"""Webhook receiver endpoint for external trigger integration.

Provides a public POST endpoint that external services (GitHub, Grafana, etc.)
can send events to, which triggers the corresponding agent.
"""

import hashlib
import hmac
import json
import re
import time
import uuid

from fastapi import APIRouter, Request
from fastapi.responses import JSONResponse
from loguru import logger
from sqlalchemy import select

from app.core.events import get_redis
from app.database import async_session
from app.models.agent import Agent
from app.models.audit import AuditLog
from app.models.trigger import AgentTrigger
from app.services.trigger_runtime import enqueue_webhook_execution
from app.services.trigger_runtime.config import AUTOMATIC_TRIGGER_EXECUTION_ENABLED

router = APIRouter(prefix="/api/webhooks", tags=["webhooks"])

RATE_LIMIT = 5  # max hits per minute per token
MAX_PAYLOAD_SIZE = 65536  # 64KB max payload
WEBHOOK_TOKEN_RE = re.compile(r"^[A-Za-z0-9_-]{32}$")


async def _record_and_count_hits(trigger_id: uuid.UUID) -> int:
    """Record the current hit in Redis and return the rolling 60-second count."""
    redis = await get_redis()
    now = time.time()
    key = f"webhook:rate:{trigger_id}"
    member = f"{now}:{hashlib.sha1(f'{trigger_id}:{now}'.encode()).hexdigest()[:8]}"
    async with redis.pipeline(transaction=True) as pipe:
        pipe.zremrangebyscore(key, 0, now - 60)
        pipe.zadd(key, {member: now})
        pipe.zcard(key)
        pipe.expire(key, 120)
        _, _, count, _ = await pipe.execute()
    return int(count)


@router.post("/t/{token}")
async def receive_webhook(token: str, request: Request):
    """Receive a webhook POST from an external service.

    Public endpoint — no authentication required.
    Security is provided by:
    - Unique, unguessable URL token
    - Mandatory HMAC-SHA256 signature verification
    - Rate limiting (5 requests/minute per token)
    - Payload size limit (64KB)
    """
    # The RC5 automation worker is deliberately maintenance-off.  Reject at
    # ingress before reading the body, touching Redis, looking up the token, or
    # enqueueing work.  Preserved enabled flags represent user desired state;
    # they must not create an unbounded pending queue while execution is paused.
    if not AUTOMATIC_TRIGGER_EXECUTION_ENABLED:
        return JSONResponse(
            {
                "ok": False,
                "error": "automatic trigger execution is temporarily paused",
            },
            status_code=503,
            headers={"Retry-After": "3600"},
        )

    # Tokens are generated by ``secrets.token_urlsafe(24)``. Reject malformed
    # attacker-controlled path segments before database or Redis work, while
    # returning the same opaque response used for an unknown valid token.
    if not WEBHOOK_TOKEN_RE.fullmatch(token):
        return JSONResponse({"ok": True})

    # Resolve one exact active trigger before allocating any Redis key. This
    # makes random-token churn read-only and keeps the rate bucket keyed by a
    # non-secret durable trigger id rather than the URL credential.
    async with async_session() as db:
        result = await db.execute(
            select(AgentTrigger)
            .where(
                AgentTrigger.type == "webhook",
                AgentTrigger.is_enabled,
                AgentTrigger.config["token"].as_string() == token,
            )
            .limit(1)
        )
        target = result.scalar_one_or_none()
        if not target:
            return JSONResponse({"ok": True})

    # Rate limiting — use per-agent limit if available
        hit_count = await _record_and_count_hits(target.id)

    # We'll check per-agent rate limit after finding the trigger below.
    # For now, apply a generous global ceiling to prevent memory abuse.
        if hit_count >= 60:  # hard ceiling: 60/min regardless of config
            logger.warning("Webhook hard rate limit exceeded")
            return JSONResponse({"ok": True}, status_code=429)

    # Payload size check
        body = await request.body()
        if len(body) > MAX_PAYLOAD_SIZE:
            logger.warning(f"Webhook payload too large: {len(body)} bytes")
            return JSONResponse({"ok": True}, status_code=413)

        # Per-agent rate limit check
        agent_result = await db.execute(select(Agent).where(Agent.id == target.agent_id))
        agent_obj = agent_result.scalar_one_or_none()
        agent_rate_limit = (agent_obj.webhook_rate_limit if agent_obj else None) or RATE_LIMIT

        # Retrieve all needed scalar fields and expunge from db session to prevent MissingGreenlet errors.
        target_id = target.id
        target_name = target.name
        target_agent_id = target.agent_id
        target_config = target.config or {}
        db.expunge(target)
        if agent_obj:
            db.expunge(agent_obj)

        # Re-check hits against agent-specific limit (hits already collected above)
        if hit_count > agent_rate_limit:  # > because current hit is already counted
            logger.warning(f"Webhook per-agent rate limit exceeded ({agent_rate_limit}/min)")
            # Log audit entry so user can see dropped webhooks
            try:
                db.add(
                    AuditLog(
                        agent_id=target_agent_id,
                        action="webhook_rate_limited",
                        details={
                            "trigger_id": str(target_id),
                            "trigger_name": target_name,
                            "limit": agent_rate_limit,
                        },
                    )
                )
                await db.commit()
            except Exception:
                pass
            return JSONResponse({"ok": True}, status_code=429)

        # URL tokens leak through logs and third-party configuration. Every
        # delivery therefore requires an independent HMAC secret.
        secret = str(target_config.get("secret") or "").strip()
        if not secret:
            logger.error(f"Blocked legacy unsigned webhook trigger {target_id}")
            return JSONResponse({"ok": False, "error": "webhook signing is not configured"}, status_code=403)

        sig_header = (
            request.headers.get("x-hub-signature-256", "")
            or request.headers.get("x-astra-signature-256", "")
        )
        expected_sig = "sha256=" + hmac.new(secret.encode(), body, hashlib.sha256).hexdigest()
        if not hmac.compare_digest(sig_header, expected_sig):
            logger.warning(f"Webhook signature mismatch for trigger {target_id}")
            return JSONResponse({"ok": False, "error": "invalid signature"}, status_code=401)

        # Parse payload
        try:
            payload_str = body.decode("utf-8")
            # Try to pretty-format JSON for readability
            payload_obj = None
            try:
                payload_obj = json.loads(payload_str)
                payload_str = json.dumps(payload_obj, ensure_ascii=False, indent=2)
            except json.JSONDecodeError:
                payload_obj = None
        except Exception:
            payload_obj = None
            payload_str = repr(body[:2000])

        execution, created = await enqueue_webhook_execution(
            db,
            trigger=target,
            body=body,
            payload_text=payload_str,
            payload_obj=payload_obj if isinstance(payload_obj, dict) else None,
            request_headers={k.lower(): v for k, v in request.headers.items()},
        )
        if not created:
            logger.info(f"Webhook duplicate ignored for trigger {target_id}")
            return JSONResponse({"ok": True})
        if execution is not None and execution.status == "failed":
            logger.error(
                "Webhook Runtime intake failed trigger_id={} status={}",
                target_id,
                execution.status,
            )
            return JSONResponse(
                {"ok": False, "error": "runtime_unavailable"},
                status_code=503,
            )

        logger.info(f"Webhook queued for trigger {target_id} (agent {target_agent_id})")

    return JSONResponse({"ok": True})
